/* IL Chats Mail v6 — Supabase Auth + caixa postal interna + preparação segura para e-mail externo.
   Nenhum segredo deve ser colocado neste arquivo. */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let sb=null,currentUser=null,currentFolder='inbox',messages=[],selectedId=null,useBrand=false,currentDraftId=null,pendingLogo=null;
const list=$('#messageList'),reader=$('#reader'),empty=$('#readerEmpty'),content=$('#readerContent');
const authUi={loginScreen:$('#loginScreen'),message:$('#authMessage'),signupMessage:$('#signupMessage'),resetMessage:$('#resetMessage')};
function toast(t){const el=$('#toast');if(!el)return;el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function setAuthMessage(el,text,ok=false){if(!el)return;el.textContent=text||'';el.classList.toggle('ok',!!ok)}
function supabaseReady(){return !!(window.supabase&&window.ILMAIL_SUPABASE_URL&&window.ILMAIL_SUPABASE_PUBLISHABLE_KEY&&window.ILMAIL_SUPABASE_PUBLISHABLE_KEY!=='COLE_AQUI_SUA_PUBLISHABLE_KEY')}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initials(name='?'){return name.split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()||'?'}
function fmtTime(d){if(!d)return '';const x=new Date(d),now=new Date();if(x.toDateString()===now.toDateString())return x.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});return x.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}
function sigKey(){return `ilmail_signature_${currentUser?.id||'guest'}`}
function sig(){try{return JSON.parse(localStorage.getItem(sigKey())||'{}')}catch{return {}}}
function signatureHtml(){const s=sig();if(!s.name&&!s.logo)return '';return `<div><b>${esc(s.name||'')}</b>${s.role?'<div>'+esc(s.role)+'</div>':''}${s.phone?'<div>'+esc(s.phone)+'</div>':''}${s.site?'<div>'+esc(s.site)+'</div>':''}${s.logo?'<img src="'+s.logo+'" alt="Logotipo">':''}</div>`}

function showMailApp(user){currentUser=user;authUi.loginScreen?.classList.add('hidden');document.body.classList.add('authenticated');const email=user?.email||'';$('#accountEmail').textContent=email;$('.account span:nth-child(2)').textContent=user?.user_metadata?.name||email.split('@')[0]||'Conta';loadMailbox();logVisit();checkAdmin()}
function showLogin(){currentUser=null;authUi.loginScreen?.classList.remove('hidden');document.body.classList.remove('authenticated');$('#accountMenu')?.classList.add('hidden')}
async function initAuth(){if(!supabaseReady()){showLogin();setAuthMessage(authUi.message,'Conecte a Publishable key do Supabase para ativar o IL Chats Mail.');return}sb=window.supabase.createClient(window.ILMAIL_SUPABASE_URL,window.ILMAIL_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await sb.auth.getSession();if(data.session)showMailApp(data.session.user);else showLogin();sb.auth.onAuthStateChange((_e,s)=>s?showMailApp(s.user):showLogin())}

$('#togglePassword')?.addEventListener('click',()=>{const i=$('#loginPassword');i.type=i.type==='password'?'text':'password'});
$('#showSignupBtn')?.addEventListener('click',()=>$('#signupDialog')?.showModal());
$('#forgotPasswordBtn')?.addEventListener('click',()=>{if($('#loginEmail')?.value)$('#resetEmail').value=$('#loginEmail').value;$('#resetDialog')?.showModal()});
$$('.dialog-close').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.close)?.close()));
$('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault();setAuthMessage(authUi.message,'');if(!sb)return setAuthMessage(authUi.message,'Supabase ainda não está conectado.');const {error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});setAuthMessage(authUi.message,error?translateError(error.message):'Login realizado.',!error)});
$('#signupForm')?.addEventListener('submit',async e=>{e.preventDefault();setAuthMessage(authUi.signupMessage,'');if(!sb)return;const name=$('#signupName').value.trim(),email=$('#signupEmail').value.trim(),password=$('#signupPassword').value;const {error}=await sb.auth.signUp({email,password,options:{data:{name},emailRedirectTo:new URL('./',location.href).href}});setAuthMessage(authUi.signupMessage,error?translateError(error.message):'Conta criada. Confira seu e-mail para confirmar o cadastro.',!error)});
$('#resetForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!sb)return;const {error}=await sb.auth.resetPasswordForEmail($('#resetEmail').value.trim(),{redirectTo:new URL('./',location.href).href});setAuthMessage(authUi.resetMessage,error?translateError(error.message):'Link de recuperação enviado.',!error)});
$('#accountBtn')?.addEventListener('click',e=>{e.stopPropagation();$('#accountMenu')?.classList.toggle('hidden')});
document.addEventListener('click',e=>{if(!e.target.closest('#accountMenu')&&!e.target.closest('#accountBtn'))$('#accountMenu')?.classList.add('hidden')});
$('#logoutBtn')?.addEventListener('click',async()=>{if(sb)await sb.auth.signOut()});
function translateError(m=''){if(/Invalid login credentials/i.test(m))return 'E-mail ou senha incorretos.';if(/Email not confirmed/i.test(m))return 'Confirme seu e-mail antes de entrar.';if(/User already registered/i.test(m))return 'Este e-mail já possui uma conta.';return m}

async function loadMailbox(){if(!sb||!currentUser)return;selectedId=null;content.classList.add('hidden');empty.classList.remove('hidden');reader.classList.remove('open');list.innerHTML='<div class="loading-mail">Carregando mensagens…</div>';
 try{
  if(currentFolder==='drafts'){
   const {data,error}=await sb.from('drafts').select('*').order('updated_at',{ascending:false});if(error)throw error;
   messages=(data||[]).map(d=>({id:d.id,folder:'drafts',sender:'Rascunho',email:d.to_email||'',subject:d.subject||'(sem assunto)',preview:(d.body||'').slice(0,100)||'Rascunho vazio',body:d.body||'',time:fmtTime(d.updated_at),created_at:d.updated_at,isDraft:true,fav:false}));
  }else{
   let q=sb.from('message_states').select('message_id,folder,is_starred,is_read,previous_folder,messages!inner(id,created_at,sender_id,recipient_id,sender_email,recipient_email,subject,body)');
   if(currentFolder==='favorites')q=q.eq('is_starred',true);else q=q.eq('folder',currentFolder);
   const {data,error}=await q.order('updated_at',{ascending:false});if(error)throw error;
   messages=(data||[]).map(r=>{const m=r.messages,isSender=m.sender_id===currentUser.id;const peer=isSender?(m.recipient_email||'Destinatário'):(m.sender_email||'Remetente');return {id:m.id,folder:r.folder,sender:isSender?'Você':peer,email:peer,subject:m.subject||'(sem assunto)',preview:(m.body||'').slice(0,100),body:m.body||'',time:fmtTime(m.created_at),created_at:m.created_at,fav:r.is_starred,is_read:r.is_read,previousFolder:r.previous_folder,isSender}});
  }
  renderList();
 }catch(err){console.error(err);list.innerHTML='<div class="mail-error">Não foi possível carregar as mensagens.<br><small>'+esc(err.message)+'</small></div>'}
}
function visibleMessages(){const q=$('#searchInput').value.trim().toLowerCase();return q?messages.filter(m=>(`${m.sender} ${m.email} ${m.subject} ${m.preview}`).toLowerCase().includes(q)):messages}
function renderList(){list.innerHTML='';const arr=visibleMessages();if(!arr.length){list.innerHTML='<div class="empty-folder">Nenhuma mensagem nesta pasta.</div>'}else arr.forEach(m=>{const el=document.createElement('div');el.className='message'+(m.id===selectedId?' selected':'')+(!m.is_read&&m.folder==='inbox'?' unread':'');el.innerHTML=`<div class="circle">${initials(m.sender)}</div><div><h4>${esc(m.sender)}</h4><strong>${esc(m.subject)}</strong><p>${esc(m.preview)}</p></div><div><time>${esc(m.time)}</time>${m.isDraft?'':'<span class="star '+(m.fav?'on':'')+'" data-star="'+m.id+'">★</span>'}</div>`;el.onclick=e=>{if(e.target.dataset.star){e.stopPropagation();toggleFav(e.target.dataset.star);return}openMessage(m.id)};list.appendChild(el)});updateCounts()}
async function updateCounts(){if(!sb||!currentUser)return;const {count}=await sb.from('message_states').select('*',{count:'exact',head:true}).eq('folder','inbox');$('#inboxCount').textContent=count??0}
async function openMessage(id){selectedId=id;const m=messages.find(x=>String(x.id)===String(id));if(!m)return;renderList();empty.classList.add('hidden');content.classList.remove('hidden');$('#readSubject').textContent=m.subject;$('#readSender').textContent=m.sender;$('#readEmail').textContent='<'+m.email+'>';$('#readBody').innerHTML=`<div class="mail-copy"><p>${esc(m.body).replace(/\n/g,'<br>')}</p></div>`;reader.classList.add('open');syncReaderActions();if(m.isDraft){openDraft(m);return}if(m.folder==='inbox'&&!m.is_read){await sb.from('message_states').update({is_read:true}).eq('message_id',m.id).eq('user_id',currentUser.id);m.is_read=true;renderList()}}
function selectedMessage(){return messages.find(m=>String(m.id)===String(selectedId))}
function syncReaderActions(){const m=selectedMessage();if(!m)return;const inTrash=m.folder==='trash';$('#restoreReadBtn')?.classList.toggle('hidden',!inTrash);$('#permanentDeleteBtn')?.classList.toggle('hidden',!inTrash);$('#deleteReadBtn')?.classList.toggle('hidden',inTrash||m.isDraft);$('#favoriteReadBtn')?.classList.toggle('hidden',m.isDraft);if($('#favoriteReadBtn'))$('#favoriteReadBtn').textContent=m.fav?'★':'☆'}
async function toggleFav(id){const m=messages.find(x=>String(x.id)===String(id));if(!m||m.isDraft)return;const next=!m.fav;const {error}=await sb.from('message_states').update({is_starred:next}).eq('message_id',m.id).eq('user_id',currentUser.id);if(error)return toast('Não foi possível atualizar o favorito');m.fav=next;renderList();syncReaderActions()}
$('#favoriteReadBtn')?.addEventListener('click',()=>{const m=selectedMessage();if(m)toggleFav(m.id)});
$('#deleteReadBtn')?.addEventListener('click',async()=>{const m=selectedMessage();if(!m)return;const {error}=await sb.from('message_states').update({previous_folder:m.folder,folder:'trash'}).eq('message_id',m.id).eq('user_id',currentUser.id);if(error)return toast('Não foi possível mover para a Lixeira');toast('Mensagem movida para a Lixeira');loadMailbox()});
$('#restoreReadBtn')?.addEventListener('click',async()=>{const m=selectedMessage();if(!m)return;const folder=m.previousFolder||'inbox';const {error}=await sb.from('message_states').update({folder,previous_folder:null}).eq('message_id',m.id).eq('user_id',currentUser.id);if(error)return toast('Não foi possível restaurar');toast('Mensagem restaurada');loadMailbox()});
$('#permanentDeleteBtn')?.addEventListener('click',async()=>{const m=selectedMessage();if(!m||!confirm('Excluir esta mensagem definitivamente da sua caixa?'))return;const {error}=await sb.rpc('delete_message_for_me',{p_message_id:m.id});if(error)return toast('Não foi possível excluir');toast('Mensagem excluída da sua caixa');loadMailbox()});
$('#mobileBackBtn')?.addEventListener('click',()=>reader.classList.remove('open'));

$$('.folder').forEach(b=>b.onclick=()=>{$$('.folder').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFolder=b.dataset.folder;loadMailbox()});
$('#searchInput')?.addEventListener('input',renderList);$('#refreshBtn')?.addEventListener('click',()=>{loadMailbox();toast('Caixa atualizada')});
$$('.tab').forEach((tab,i)=>tab.addEventListener('click',()=>{$$('.tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');currentFolder=i===2?'favorites':'inbox';$$('.folder').forEach(x=>x.classList.toggle('active',x.dataset.folder===currentFolder));loadMailbox()}));

$('#composeBtn')?.addEventListener('click',()=>{currentDraftId=null;$('#composeForm').reset();$('#signaturePreview').classList.add('hidden');useBrand=false;$('#composeDialog').showModal()});
$('#composeForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!sb)return;const to=$('#toInput').value.trim(),subject=$('#subjectInput').value.trim()||'(sem assunto)';let body=$('#bodyInput').value;if(useBrand){const s=sig();body+='\n\n'+[s.name,s.role,s.phone,s.site].filter(Boolean).join('\n')}
 const btn=e.submitter;btn.disabled=true;btn.textContent='Enviando…';const {data:recipient}=await sb.from('profiles').select('id').eq('email',to).maybeSingle(); let error; if(recipient){({error}=await sb.rpc('send_internal_mail',{p_to_email:to,p_subject:subject,p_body:body}));}else{const r=await sb.functions.invoke('send-external-email',{body:{to,subject,body}});error=r.error;}btn.disabled=false;btn.textContent='Enviar';if(error){toast('Não foi possível enviar. Verifique a configuração do provedor de e-mail: '+error.message);return}
 if(currentDraftId)await sb.from('drafts').delete().eq('id',currentDraftId);$('#composeDialog').close();e.target.reset();useBrand=false;currentDraftId=null;toast('Mensagem enviada');currentFolder='sent';$$('.folder').forEach(x=>x.classList.toggle('active',x.dataset.folder==='sent'));loadMailbox()});
$('#saveDraftBtn')?.addEventListener('click',async()=>{if(!sb)return;const payload={user_id:currentUser.id,to_email:$('#toInput').value.trim()||null,subject:$('#subjectInput').value.trim()||null,body:$('#bodyInput').value,updated_at:new Date().toISOString()};let error;if(currentDraftId)({error}=await sb.from('drafts').update(payload).eq('id',currentDraftId));else({error}=await sb.from('drafts').insert(payload));if(error)return toast('Não foi possível salvar o rascunho');$('#composeDialog').close();toast('Rascunho salvo');currentFolder='drafts';$$('.folder').forEach(x=>x.classList.toggle('active',x.dataset.folder==='drafts'));loadMailbox()});
function openDraft(m){$('#composeDialog').showModal();currentDraftId=m.id;$('#toInput').value=m.email||'';$('#subjectInput').value=m.subject==='(sem assunto)'?'':m.subject;$('#bodyInput').value=m.body||'';reader.classList.remove('open')}

$('#brandToggle')?.addEventListener('click',()=>{useBrand=!useBrand;const p=$('#signaturePreview');if(useBrand){p.innerHTML=signatureHtml()||'Configure sua marca em Configurações.';p.classList.remove('hidden')}else p.classList.add('hidden')});
$('#attachInput')?.addEventListener('change',e=>{const n=e.target.files.length;$('#attachInfo').textContent=n?`${n} arquivo(s) selecionado(s) — anexos reais entram na próxima etapa`:'';if(n)toast('Anexos ainda não são enviados nesta versão interna.')});
$('#settingsBtn')?.addEventListener('click',()=>{loadSettings();$('#settingsDialog').showModal()});
function loadSettings(){const s=sig();$('#sigName').value=s.name||'';$('#sigRole').value=s.role||'';$('#sigPhone').value=s.phone||'';$('#sigSite').value=s.site||'';$('#savedLogo').innerHTML=s.logo?`<img src="${s.logo}" alt="Logo salvo">`:''}
$('#sigLogo')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{pendingLogo=r.result;$('#savedLogo').innerHTML=`<img src="${pendingLogo}" alt="Prévia">`};r.readAsDataURL(f)});
$('#settingsForm')?.addEventListener('submit',e=>{e.preventDefault();const old=sig(),s={name:$('#sigName').value,role:$('#sigRole').value,phone:$('#sigPhone').value,site:$('#sigSite').value,logo:pendingLogo||old.logo||''};localStorage.setItem(sigKey(),JSON.stringify(s));pendingLogo=null;$('#settingsDialog').close();toast('Sua marca foi salva')});

$$('.reply-actions button').forEach((btn,i)=>btn.addEventListener('click',()=>{const m=selectedMessage();if(!m||m.isDraft)return;$('#composeDialog').showModal();currentDraftId=null;if(i===2){$('#toInput').value='';$('#subjectInput').value=m.subject.startsWith('Enc:')?m.subject:'Enc: '+m.subject;$('#bodyInput').value='\n\n--- Mensagem encaminhada ---\n'+m.body}else{$('#toInput').value=m.email||'';$('#subjectInput').value=m.subject.startsWith('Re:')?m.subject:'Re: '+m.subject;$('#bodyInput').value='\n\n--- Mensagem original ---\n'+m.body}}));
$('#aboutBtn')?.addEventListener('click',()=>$('#aboutDialog').showModal());$('#proMailBtn')?.addEventListener('click',()=>$('#proMailDialog').showModal());

async function checkAdmin(){if(!sb||!currentUser)return;const {data}=await sb.from('admins').select('user_id').eq('user_id',currentUser.id).maybeSingle();$('#adminBtn')?.classList.toggle('hidden',!data)}
$('#adminBtn')?.addEventListener('click',async()=>{if(!sb)return;$('#adminDialog').showModal();$('#adminStats').innerHTML='<div class="loading-mail">Carregando estatísticas…</div>';const {data,error}=await sb.rpc('admin_dashboard');if(error){$('#adminStats').innerHTML='<div class="mail-error">'+esc(error.message)+'</div>';return}const d=data||{},countries=d.countries||[];$('#adminStats').innerHTML=`<div class="admin-cards"><div><b>${d.registered_accounts||0}</b><span>Contas cadastradas</span></div><div><b>${d.visits||0}</b><span>Visitas registradas</span></div><div><b>${d.leads||0}</b><span>Leads</span></div><div><b>${d.customers||0}</b><span>Clientes finalizados</span></div><div><b>${d.lead_conversion||0}%</b><span>Leads que viraram clientes</span></div><div><b>${d.active_7d||0}</b><span>Ativos nos últimos 7 dias</span></div><div><b>${d.messages_sent||0}</b><span>Mensagens enviadas</span></div></div><h3>Visitas por país/região do navegador</h3><div class="country-list">${countries.length?countries.map(c=>`<div><span>${esc(c.country_code||'--')}</span><b>${c.count}</b></div>`).join(''):'<small>Ainda não há dados.</small>'}</div><p class="admin-note">Por privacidade, esta versão não coleta IP nem localização precisa. O país/região é aproximado pelo idioma/região informado pelo navegador.</p>`});
async function logVisit(){if(!sb||!currentUser||sessionStorage.getItem('ilmail_visit_logged'))return;let cc='--';const loc=navigator.language||'';if(loc.includes('-'))cc=loc.split('-').pop().toUpperCase();const {error}=await sb.from('visits').insert({user_id:currentUser.id,country_code:cc,locale:loc});if(!error)sessionStorage.setItem('ilmail_visit_logged','1')}

initAuth();
